services:
  - type: web
    name: sdp-selpuro
    runtime: node
    plan: free
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
